version: 2
updates:
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "egdavid"
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "egdavid"
    labels:
      - "dependencies"
      - "github-actions"