[package]
name = "rusty_socks"
version = "0.1.0"
edition = "2021"
authors = ["David EUGENE - egdavid@GitHub"]
description = "Lightweight WebSocket server written in Rust"
readme = "README.md"
license = "MIT"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
uuid = { version = "1.3", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
futures-util = "0.3"
dotenvy = "0.15"
jsonwebtoken = "9.2"
argon2 = "0.5"
rand = "0.8"
base64 = "0.22"

[dev-dependencies]
reqwest = { version = "0.11", features = ["json", "stream", "blocking"] }
tokio-tungstenite = "0.21"
futures-util = "0.3"

[[bin]]
name = "rusty_socks"
path = "src/bin/server.rs"